version: '3'
services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init-queries:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  web:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    volumes:
      - ./app/api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
